name: Check Examples

on:
  schedule:
    - cron: '23 3 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          go run ./lib/utils/get-browser
          go test -run Example ./...
          go test ./lib/examples/e2e-testing
